export const LessonPlane = [
  {
    id: 1,
    title: "Основи Git та GitHub",
    description:
      "Git є системою контролю версій, яка дозволяє зберігати та відстежувати зміни у коді та визначати, які саме зміни були внесені та хто їх вніс. Git дозволяє працювати зі структурованими гілками, які дозволяють паралельно розробляти різні функції, фіксувати баги та вирішувати конфлікти. GitHub, з іншого боку, є веб-сервісом, який надає зручний інтерфейс для зберігання та розповсюдження коду, який зберігається за допомогою Git. GitHub дозволяє розробникам співпрацювати над проектами, обговорювати зміни, стежити за питаннями, пропозиціями та внесенням змін.",
    image: "https://picsum.photos/id/123/200/300",
    url: "/GitHub",
  },
  {
    id: 2,
    title: "Змінні та типи",
    description: "Lesson 1 description",
    image: "https://picsum.photos/id/123/200/300",
    url: "/M1L1",
  },
  {
    id: 3,
    title: "Розгалуження та цикли",
    description: "Lesson 1 description",
    image: "https://picsum.photos/id/123/200/300",
    url: "/M1L2",
  },
  {
    id: 4,
    title: "Масиви",
    description: "Lesson 1 description",
    image: "https://picsum.photos/id/123/200/300",
    url: "/Arrey",
  },
  {
    id: 5,
    title: "Функції",
    description: "Lesson 1 description",
    image: "https://picsum.photos/id/123/200/300",
    url: "/Function",
  },
  {
    id: 6,
    title: "Обʼєкт",
    description: "Lesson 1 description",
    image: "https://picsum.photos/id/123/200/300",

    url: "/Object",
  },
  {
    id: 7,
    title: "Деструктуризація та spread/rest",
    description: "Lesson 1 description",
    image: "https://picsum.photos/id/123/200/300",
    url: "/SpreadRest",
  },
  {
    id: 8,
    title: "CallBack та стрілочні цункції",
    description: "Lesson 1 description",
    image: "https://picsum.photos/id/123/200/300",
    url: "/CallBack",
  },
  {
    id: 9,
    title: "Перебираючі методи масиву",
    description: "Lesson 1 description",
    image: "https://picsum.photos/id/123/200/300",
    url: "/ArrayMethod",
  },
  {
    id: 10,
    title: "Ключове слово this",
    description: "Lesson 1 description",
    image: "https://picsum.photos/id/123/200/300",
    url: "/This",
  },
  {
    id: 10,
    title: "Ключове слово this",
    description: "Lesson 1 description",
    image: "https://picsum.photos/id/123/200/300",
    url: "/This",
  },
  {
    id: 11,
    title: "Прототипи та класи",
    description: "Lesson 1 description",
    image: "https://picsum.photos/id/123/200/300",
    url: "/Prototipe",
  },
];
